[env]
PROJECT="osakamenesu"

[tools]
node = "20.17.0"
python = "3.11.5"

[tasks.dev]
description = "Start docker-compose dev stack"
run = "make osakamenesu-dev"

[tasks.deploy]
description = "Rotate credentials and deploy API"
run = "services/api/scripts/deploy_api.sh --rotate"

[tasks.magic_link]
description = "Request a dev magic link and print the URL"
run = "services/api/scripts/dev_magic_link.sh"

[tasks.fix_quarantine]
description = "Remove macOS quarantine/provenance attributes"
script = [
  "if [ \"${1:-} \" = \"\" ]; then", 
  "  echo 'usage: mise run fix_quarantine <path>' >&2", 
  "  exit 1", 
  "fi", 
  "./tools/fix-quarantine.sh $1"
]
arguments = ["path"]
