repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: local
    hooks:
      - id: npm-lint
        name: npm run lint
        entry: npm run lint
        language: system
        types_or: [javascript, typescript]
        pass_filenames: false
      - id: npm-typecheck
        name: npm run typecheck
        entry: npm run typecheck
        language: system
        types_or: [javascript, typescript]
        pass_filenames: false
      - id: backend-tests
        name: pytest services/api
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        additional_dependencies: []
        files: ^services/api/
